/**
 * Project Tools - CRUD operations for projects
 */

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import { TcsErpApiClient } from '../api-client.js';

export const projectTools: Tool[] = [
  {
    name: 'list_projects',
    description: 'List projects with optional filters (status, partner, date range). Returns paginated results.',
    inputSchema: {
      type: 'object',
      properties: {
        status: { type: 'string', description: 'Filter by project status' },
        partner_id: { type: 'number', description: 'Filter by partner/client ID' },
        search: { type: 'string', description: 'Search projects by name or number' },
        page: { type: 'number', description: 'Page number for pagination' },
        per_page: { type: 'number', description: 'Items per page (max 100)' },
      },
    },
  },
  {
    name: 'get_project',
    description: 'Get detailed project information by ID, optionally including related data (rooms, cabinets).',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'number', description: 'Project ID' },
        include: {
          type: 'array',
          items: { type: 'string' },
          description: 'Related data to include: rooms, cabinets, partner, tasks',
        },
      },
      required: ['id'],
    },
  },
  {
    name: 'create_project',
    description: 'Create a new project with optional auto-generation of name/number and batch room creation.',
    inputSchema: {
      type: 'object',
      properties: {
        name: { type: 'string', description: 'Project name (auto-generated if auto_generate_name=true)' },
        project_number: { type: 'string', description: 'Project number (auto-generated by default)' },
        auto_generate_number: { type: 'boolean', description: 'Auto-generate project number (default: true)' },
        auto_generate_name: { type: 'boolean', description: 'Auto-generate name from address/partner (default: false)' },
        partner_id: { type: 'number', description: 'Associated partner/client ID' },
        project_type: { type: 'string', description: 'Project type: residential, commercial, renovation' },
        description: { type: 'string', description: 'Project description' },
        stage_id: { type: 'number', description: 'Project stage ID' },
        estimated_linear_feet: { type: 'number', description: 'Total estimated linear feet' },
        address: {
          type: 'object',
          description: 'Project address',
          properties: {
            street1: { type: 'string', description: 'Street address' },
            street2: { type: 'string', description: 'Street address line 2' },
            city: { type: 'string', description: 'City' },
            state: { type: 'string', description: 'State' },
            zip: { type: 'string', description: 'ZIP code' },
          },
        },
        rooms: {
          type: 'array',
          description: 'Rooms to create with the project',
          items: {
            type: 'object',
            properties: {
              name: { type: 'string', description: 'Room name (e.g., Kitchen, Master Bath)' },
              room_type: { type: 'string', description: 'Room type: kitchen, bathroom, closet, laundry, office, other' },
              linear_feet: { type: 'number', description: 'Estimated linear feet for this room' },
              cabinet_level: { type: 'string', description: 'Cabinet tier: 1-5 (default: 2)' },
              material_category: { type: 'string', description: 'Material: stain_grade, paint_grade, melamine' },
              finish_option: { type: 'string', description: 'Finish: unfinished, primed, painted, stained' },
            },
            required: ['name'],
          },
        },
        tags: {
          type: 'array',
          items: { type: 'number' },
          description: 'Tag IDs to associate with the project',
        },
        calculate_production_estimate: { type: 'boolean', description: 'Calculate production estimate (default: false)' },
      },
    },
  },
  {
    name: 'update_project',
    description: 'Update an existing project with new values.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'number', description: 'Project ID to update' },
        name: { type: 'string', description: 'New project name' },
        project_number: { type: 'string', description: 'New project number' },
        partner_id: { type: 'number', description: 'New partner ID' },
        description: { type: 'string', description: 'New description' },
        stage_id: { type: 'number', description: 'New stage ID' },
        status: { type: 'string', description: 'New status' },
      },
      required: ['id'],
    },
  },
  {
    name: 'delete_project',
    description: 'Delete a project (soft delete). This will also affect related rooms and cabinets.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'number', description: 'Project ID to delete' },
      },
      required: ['id'],
    },
  },
  {
    name: 'get_project_tree',
    description: 'Get full project hierarchy: rooms -> locations -> cabinet runs -> cabinets.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'number', description: 'Project ID' },
      },
      required: ['id'],
    },
  },
  {
    name: 'change_project_stage',
    description: 'Change project production stage. Triggers webhooks for automation.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'number', description: 'Project ID' },
        stage: {
          type: 'string',
          enum: ['discovery', 'design', 'sourcing', 'material_reserved', 'material_issued', 'production', 'delivery'],
          description: 'New production stage',
        },
      },
      required: ['id', 'stage'],
    },
  },
  {
    name: 'calculate_project',
    description: 'Calculate and update project totals (linear feet, cabinet count, doors, drawers, estimated value).',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'number', description: 'Project ID' },
      },
      required: ['id'],
    },
  },
  // Project Workflow Actions
  {
    name: 'clone_project',
    description: 'Clone/duplicate a project including all rooms, locations, cabinet runs, and cabinets.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'number', description: 'Project ID to clone' },
        new_name: { type: 'string', description: 'Name for the cloned project' },
        include_tasks: { type: 'boolean', description: 'Include tasks in clone (default false)' },
        include_bom: { type: 'boolean', description: 'Include BOM in clone (default false)' },
      },
      required: ['id'],
    },
  },
  {
    name: 'get_project_gate_status',
    description: 'Get project gate/milestone status showing completion of requirements for each phase.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'number', description: 'Project ID' },
      },
      required: ['id'],
    },
  },
  {
    name: 'get_project_bom',
    description: 'Get the bill of materials for a project with all materials, hardware, and components needed.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'number', description: 'Project ID' },
      },
      required: ['id'],
    },
  },
  {
    name: 'generate_project_order',
    description: 'Generate a sales order from a project based on its specifications and pricing.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'number', description: 'Project ID' },
        include_optional_items: { type: 'boolean', description: 'Include optional line items' },
        pricing_method: { type: 'string', description: 'Pricing method (linear_foot, per_cabinet, itemized)' },
      },
      required: ['id'],
    },
  },
];

export async function handleProjectTool(
  client: TcsErpApiClient,
  toolName: string,
  args: Record<string, unknown>
): Promise<unknown> {
  switch (toolName) {
    case 'list_projects':
      return client.listProjects(args);
    case 'get_project':
      return client.getProject(args.id as number, args.include as string[] | undefined);
    case 'create_project':
      return client.createProject(args);
    case 'update_project': {
      const { id, ...data } = args;
      return client.updateProject(id as number, data);
    }
    case 'delete_project':
      return client.deleteProject(args.id as number);
    case 'get_project_tree':
      return client.getProjectTree(args.id as number);
    case 'change_project_stage':
      return client.changeProjectStage(args.id as number, args.stage as string);
    case 'calculate_project':
      return client.calculateProject(args.id as number);
    case 'clone_project':
      return client.cloneProject(args.id as number, args);
    case 'get_project_gate_status':
      return client.getProjectGateStatus(args.id as number);
    case 'get_project_bom':
      return client.getProjectBom(args.id as number);
    case 'generate_project_order':
      return client.generateProjectOrder(args.id as number, args);
    default:
      throw new Error(`Unknown project tool: ${toolName}`);
  }
}
